delimiter $

/* IF THE MOVIE WAS RETURNED, IT WILL BE REMOVED FROM RENTED LIST */
CREATE DEFINER = CURRENT_USER TRIGGER `video_store`.`video_AFTER_INSERT` AFTER INSERT ON `video` FOR EACH ROW
BEGIN
	DELETE FROM rental WHERE return_date = 'available';
END

/* IF NEW MOVIE IS RENTED WILL SET THE VIDEO TO RENTED IN THE VIDEO TABLE */
CREATE DEFINER = CURRENT_USER TRIGGER `video_store`.`rental_AFTER_INSERT` AFTER INSERT ON `rental` FOR EACH ROW
BEGIN
	Set video.video_rented = 'rented';
END

delimiter ;